version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=development
      - PORT=5454
      - BASE_URL=http://apalabajar.com
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://apalabajar.com:5454/api
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
