version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=development
      - PORT=5454
      - BASE_URL=http://10.128.0.2:3000
  client:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_URL=http://10.128.0.2:5454/api
